config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'users/autocomplete_user_name'


  resources :users do
    member do
      get :following
      get :timeline , as: 'timeline'
    end
  end

  resources :groups
  resources :relationships, only: [:create, :destroy]
  root to: 'users#timeline'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/notifications/json', to: 'notifications#list', via: 'get'
  match '/notifications', to: 'notifications#index', via: 'get'
  match '/notifications', to: 'notifications#update', via: 'post'

  #####################resturants ########################

  get 'restaurants', to: 'restaurants#index', as: 'restaurants_list'
  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  post 'restaurants/:id', to: 'orders#create', as: 'make_order'
  get 'orders/restaurants/join/:id', to: 'restaurants#join_order', as: 'join_order'
  patch 'orders/restaurants/join/:id', to: 'orders#join_order_update'

  ###################### orders ############################

  resources :orders do
  end

  get 'invitations', to: 'orders#invitations'


end

app/models/user.rb
class User < ActiveRecord::Base
  include PublicActivity::Common

  has_attached_file :avatar, :styles => {:medium => "300x300>", :thumb => "100x100#"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

########################################## relations ##########################
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :orders
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
           class_name: "Relationship",
           dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :selfOrders, class_name: 'Order', foreign_key: 'owner_id'
  has_many :items, class_name: 'ItemsOrder'
  scope :name_like, -> (name) { where("name like ? ", name) }



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable, :zxcvbnable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]


  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
    end
  end


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "google_oauth2") if is_navigational_format?
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:timeline, :index, :show, :following]
  before_action :correct_user,   only: []
  autocomplete :user, :name, :full => true
  respond_to :html, :js

  def index
    @users = User.paginate(page: params[:page]).where.not(id: current_user)
    if params[:search]
      @users = User.name_like("%#{params[:search]}%").order('name').paginate(page: params[:page])
    else
    end
  end

  def show
    @activities = PublicActivity::Activity.order('created_at desc').where(owner_id: params[:id])
    begin
      @user = User.find(params[:id])
    rescue Exception => e
       logger.debug "#{e.class}"
       redirect_to root_url
    end
  end


  def timeline
      @activities = PublicActivity::Activity.order('created_at desc').where(owner_id: current_user.followed_users, owner_type: 'User')
      @orders = Order.where(owner_id:current_user.id).order('created_at desc')
  end


  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :phone, :bio)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Add Contact", class: "btn btn-primary btn-block" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless @user==current_user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Delete Contact", class: "btn btn-block" %>
<% end %>

app/views/users/_user.html.erb
<div class="col-md-4" style="margin-top: 20px;">
  <%= image_tag(user.avatar.url, class: "img-circle", alt: "User profile picture", :style => 'margin-left: 15px;width: 80px;margin-top:25px;  ') %>
	<%= link_to user.name, user , :style => 'padding-left:5px;font-size: 20px;' %>
		<!-- <div id="follow_form"> -->
 	<% if current_user != user %>
 		<% if current_user.following?(user) %>
  			<%= form_for(current_user.relationships.find_by(followed_id: user.id),
             html: { method: :delete }) do |f| %>
			 <%= f.submit "Delete Contact",class: "btn btn-large", style: "margin-left: 100px; margin-top:-60px;"%>
			<% end %>
		<% else %>
			<%= form_for(current_user.relationships.build(followed_id: user.id)) do |f| %>
  					<div><%= f.hidden_field :followed_id %></div>
  					<%= f.submit "Add Contact",class: "btn btn-primary", style: "margin-left: 100px; margin-top:-60px;"%>
				<% end %>
 		<% end %>
 	<% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<section class="content-header">
  <h1>
    All Users
  </h1>
</section>

<!-- Main content -->
<section class="content">
	<%= will_paginate %>

	<%= form_tag(users_path, :method => "get", id: "search-form") do%>
	<!-- text field tag=action,args,identifier,placeholdertext... -->
	<div class="box-body">
	<div class="input-group">
	<span class="input-group-addon">@</span>
		<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Friends", style: "width: 500px;" ,type: "Add Friend", data: {autocomplete: users_autocomplete_user_name_path} %>  
		<%= submit_tag "Search", class: "btn btn-primary" %>
		<%end%>
	</div>
	</div>



	<div class="row" style="overflow-y: scroll; height:440px;width:98%;">
	  	<%= render @users %>
	</div>

	<%= will_paginate %>
</section><!-- /.content -->

app/views/users/index.js.erb
$('#users').html("<%= escape_javascript (render partial: '@user') %>");

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<!-- Content Header (Page header) -->
<% content_for :head do %>
    <%= @user.name %>'s Profile
<% end %>

<!-- Main content -->
<div class="row">
  <div class="col-md-3">

    <!-- Profile Image -->
    <div class="box box-primary">
      <div class="box-body box-profile">
        <%= image_tag(@user.avatar.url, class: "profile-user-img img-responsive img-circle", alt: "User profile picture") %>
        <h3 class="profile-username text-center"><%= @user.name %></h3>

        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>Contacts</b> <a class="pull-right"><%= @user.followed_users.count %></a>
          </li>
        </ul>
        <%= render 'follow_form' if user_signed_in? %>
      </div><!-- /.box-body -->
    </div><!-- /.box -->

    <!-- About Me Box -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">About Me</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <%= @user.bio %>
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->
  <div class="col-md-9">
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#activity" data-toggle="tab">Activity</a></li>
        <% if current_user.id == @user.id %>
            <li><a href="#settings" data-toggle="tab">Settings</a></li>
        <% end %>
      </ul>
      <div class="tab-content">
        <div class="active tab-pane" id="activity">
          <div class="box-body">
            <ul class="todo-list ui-sortable" style="overflow-x: hidden; max-height: 400px;">
              <% @activities.each do |activity| %>
                  <% if activity %>
                      <li>
                        <span class="text"><%= render_activity activity %></span>
                        <!-- <small class="label label-info"><i class="fa fa-clock-o"></i> 4 hours</small> -->
                      </li>
                  <% end %>
              <% end %>
            </ul>
          </div>
        </div><!-- /.tab-pane -->
        <div class="tab-pane" id="settings">
          <%= link_to "Edit Settings", edit_user_registration_path %>
        </div><!-- /.tab-pane -->
      </div><!-- /.tab-content -->
    </div><!-- /.nav-tabs-custom -->
  </div><!-- /.col -->
</div><!-- /.row -->

app/views/users/show_follow.html.erb
<% provide(:title, 'Friends') %>

<section class="content-header">
  <h1>
    Friends List
  </h1>
</section>

<!-- Main content -->
<section class="content">

	<%= will_paginate %>

	<%= form_tag(users_path, :method => "get", id: "search-form") do%>
	<!-- text field tag=action,args,identifier,placeholdertext... -->
	<div class="box-body">
	<div class="input-group">
	<span class="input-group-addon">@</span>
	  <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Friends", style: "width: 500px;" ,type: "Add Friend", data: {autocomplete: users_autocomplete_user_name_path} %>  
	  <%= submit_tag "Search", class: "btn btn-primary" %>
	  <%end%>
	</div>
	</div>

	<div class="row" style="overflow-y: scroll; height:440px;width:98%;">
	    <%= render @users %>
	</div>

	<%= will_paginate %>
</section><!-- /.content -->

app/views/users/timeline.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Home
    <small>Control Panel</small>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <!-- Your Page Content Here -->
  <br />
  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">
        <div class="box-header">
          <i class="fa fa-list-alt"></i>
          <h3 class="box-title">Latest Orders</h3>
        </div>
        <div class="box-body">
          <ul class="todo-list ui-sortable" style="overflow-x: hidden; max-height: 400px;">
            <% if @activities.blank? %>
                <li>
                  <span class="text">No orders</span>
                </li>
            <% else %>
                <% @orders.each do |order| %>
                    <% if order %>
                        <li>
                          You made order from
                          <span class="text"><%= order.restaurant.name  %></span>
                          at
                          <small class="label label-info"><i class="fa fa-clock-o"></i>
                            <%= order.created_at  %></small>
                        </li>
                    <% end %>
                <% end %>
            <% end %>
          </ul>
        </div>
        <div class="box-footer">
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="box box-danger">
        <div class="box-header">
          <i class="fa fa-rss"></i>
          <h3 class="box-title">Friends Activity</h3>
        </div>
        <div class="box-body">
          <ul class="todo-list ui-sortable" style="overflow-x: hidden; max-height: 400px;">
          <% if @activities.blank? %>
            <li>
              <span class="text">No activities</span>
            </li>
          <% else %>
            <% @activities.each do |activity| %>
              <% if activity %>
                <li>
                  <span class="text"><%= render_activity activity %></span>
                  <!-- <small class="label label-info"><i class="fa fa-clock-o"></i> 4 hours</small> -->
                </li>
              <% end %>    
            <% end %>
          <% end %>
          </ul>
        </div>
        <div class="box-footer">
        </div>
      </div>
    </div>
  </div>
</section><!-- /.content -->